fantasyIn/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from players import urls as players_urls
from players import views as players_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', players_views.home, name='home'), 
    url(r'^(?P<tournament_id>[0-9]+)/$', players_views.tournament_home, name='tournament_home'),
    url(r'^(?P<tournament_id>[0-9]+)/matches/$', players_views.matches, name='matches'),
    url(r'^(?P<tournament_id>[0-9]+)/matches/(?P<match_id>[0-9]+)/$', players_views.match_detail, name='match_detail'),
    url(r'^(?P<tournament_id>[0-9]+)/teams/$', players_views.teams, name='teams'),
    url(r'^(?P<tournament_id>[0-9]+)/teams/(?P<team_id>[0-9]+)/$', players_views.team_detail, name='team_detail'),
    url(r'^(?P<tournament_id>[0-9]+)/players/$', players_views.players, name='players'),
    url(r'^(?P<tournament_id>[0-9]+)/players/(?P<player_id>[0-9]+)/$', players_views.player_detail, name='player_detail'),
    url(r'^(?P<tournament_id>[0-9]+)/results/$', players_views.pmr, name='pmr'),
    url(r'^admin/', include(admin.site.urls)),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

players/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from players import views

urlpatterns = [

]

players/models.py
from django.db import models
from django.db.models import Count, Min, Sum, Avg

class Tournament(models.Model):
	name = models.CharField(max_length=1024)
	url = models.CharField(max_length=1024)
	date = models.DateField()
	next_tour = models.IntegerField(null=True)
	
class Player(models.Model):
	fantasy_id = models.IntegerField(default=0)
	tournament = models.ForeignKey('Tournament')
	team = models.ForeignKey('Team')
	amplua_choice = ((1, 'Вратарь'),
					(2, 'Защитник'),
					(4, 'Нападающий'),
					(3, 'Полузащитник'),)
	amplua = models.IntegerField(max_length=1, choices=amplua_choice, null=True, default=1)
	name = models.CharField(max_length=50)
	price = models.DecimalField(max_digits=3, decimal_places=1, null=True)
	points = models.IntegerField(max_length=3, null=True)
	userchoosed = models.FloatField(null=True)
	url = models.CharField(max_length=1024)
	url_img = models.CharField(max_length=1024)
	isstar=models.BooleanField(default=False)
	goals = models.IntegerField(default=0)
	passes = models.IntegerField(default=0)
	clean_sheets=models.IntegerField(default=0)
	minutes=models.IntegerField(default=0)

class Team(models.Model):
	tournament = models.ForeignKey('Tournament')
	fantasy_id = models.IntegerField(default=0)
	name = models.CharField(max_length=50)
	url = models.CharField(max_length=1024)
	url_img = models.CharField(max_length=1024, null=True)
	place = models.IntegerField(max_length = 2, null=True)
	points = models.IntegerField(max_length=2, null=True)
	fantasypoints = models.IntegerField(null=True)
	win = models.IntegerField(max_length=2, null=True)
	lose = models.IntegerField(max_length=2, null=True)
	drawn = models.IntegerField(max_length=2, null=True)
	score_goals = models.IntegerField(max_length=3, null=True)
	lose_goals = models.IntegerField(max_length=3, null=True)
	country_choices = (('RU', 'Russia'))

	def goalkeeper_points(self):
		return PlayerMatchResult.objects.filter(player__team=self,player__amplua=1).aggregate(line_points=Sum('points'))['line_points']

	def defs_points(self):
		return PlayerMatchResult.objects.filter(player__team=self,player__amplua=2).aggregate(line_points=Sum('points'))['line_points']

	def mids_points(self):
		return PlayerMatchResult.objects.filter(player__team=self,player__amplua=3).aggregate(line_points=Sum('points'))['line_points']

	def forwards_points(self):
		return PlayerMatchResult.objects.filter(player__team=self,player__amplua=4).aggregate(line_points=Sum('points'))['line_points']


class Match(models.Model):
	tournament = models.ForeignKey('Tournament')
	home_team = models.ForeignKey('Team', related_name = 'home', default=0)
	visit_team = models.ForeignKey('Team', related_name='visit',default=0)
	home_team_goals = models.IntegerField(max_length = 2, null=True)
	visit_team_goals = models.IntegerField(max_length=2, null=True)
	url = models.CharField(max_length=1024)
	date = models.DateField()
	tour = models.IntegerField(null=True)
	visitors = models.IntegerField(null=True)

	def full_name(self):

		if self.home_team_goals==None:
			home_team_goals="-"
		else:
			home_team_goals = self.home_team_goals
		if self.visit_team_goals==None:
			visit_team_goals = "-"
		else:
			visit_team_goals = self.visit_team_goals

		return "{0} {1} : {2} {3}".format(self.home_team.name, 
			home_team_goals, visit_team_goals,
			self.visit_team.name)
	
	def home_team_points(self):
		return PlayerMatchResult.objects.filter(match = self, player__team=self.home_team).aggregate(match_points=Sum('points'))['match_points']

	def visit_team_points(self):
		return PlayerMatchResult.objects.filter(match = self, player__team=self.visit_team).aggregate(match_points=Sum('points'))['match_points']


class PlayerMatchResult(models.Model):
	match = models.ForeignKey('Match')
	player = models.ForeignKey('Player', default=0)
	minute = models.IntegerField(max_length = 3)
	goals = models.IntegerField(max_length=2)
	passes = models.IntegerField(max_length = 2)
	lose_penalty = models.IntegerField(max_length = 2)
	yellow_cards = models.IntegerField(max_length=2)
	red_cards = models.IntegerField(max_length=2)
	clean_sheet = models.BooleanField()
	points = models.IntegerField(max_length=2)

players/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.db.models import Count, Min, Sum, Avg, Q
import datetime

from .models import Player, Match, Team, PlayerMatchResult, Tournament

def home(request):
	
	tournament_list = Tournament.objects.all()
	template = loader.get_template('index.html')
	context = RequestContext(request, {'tournament_list':tournament_list, })
	return HttpResponse(template.render(context))
	
def tournament_home(request, tournament_id):
	tournament = Tournament.objects.get(id = tournament_id)
	points_count = PlayerMatchResult.objects.filter(match__tournament_id=tournament_id).aggregate(total_points = Sum('points'))['total_points']
	match_list = Match.objects.filter(tournament_id=tournament_id, tour__lte=tournament.next_tour).order_by('date')
	players_list = Player.objects.filter(tournament=tournament).exclude(points=None).order_by('-points')[:3]
	team_list = Team.objects.filter(tournament=tournament).order_by('-fantasypoints')[:3]
	template = loader.get_template('home_tournament.html')
	context = RequestContext(request, {'players_count': Player.objects.filter(tournament=tournament).count(),
	 'match_count': match_list.count(), 'team_count': Team.objects.filter(tournament=tournament).count(),
	  'points_count': points_count, 'tournament': tournament, 'match_list':match_list, 'players_list':players_list, 'team_list':team_list})
	return HttpResponse(template.render(context))

def teams(request, tournament_id):
	#points_count = PlayerMatchResult.objects.aggregate(total_points = Sum('points'))['total_points']
	tournament = Tournament.objects.get(id = tournament_id)
	match_list = Match.objects.filter(tournament_id=tournament_id, tour__lte=tournament.next_tour-1).order_by('date')
	team_list = Team.objects.filter(tournament_id = tournament_id)
	for team in team_list:
		team.result_list=[]
		for match in match_list:
			if match.home_team.id == team.id:
				team.result_list = team.result_list + [match.home_team_points()]
			if match.visit_team.id == team.id:
				team.result_list = team.result_list + [match.visit_team_points()]

		#print (team.result_list)
		#team.result_list = PlayerMatchResult.objects.filter(player__team=team).annotate
	all_points = PlayerMatchResult.objects.filter(match__tournament_id=tournament_id).aggregate(total_points = Sum('points'))['total_points']

	for team in team_list:
		team.players_points = int(PlayerMatchResult.objects.filter(match__tournament_id=tournament_id, player__team=team).aggregate(team_players_points=Sum('points'))['team_players_points'])
		team.progress = (team.players_points/all_points)*100


	team_list = sorted(team_list, key=lambda team:team.players_points, reverse=True)
	#print (type(team_list))

	#team_list.sort(key=team.players_points)
	template = loader.get_template('teams.html')
	context = RequestContext(request, {'team_list': team_list, 'tournament': tournament, 'match_list':match_list })

	return HttpResponse(template.render(context))

def matches(request, tournament_id):
	tournament = Tournament.objects.get(id = tournament_id)
	match_list = Match.objects.filter(tournament_id=tournament_id).order_by('date')
	for match in match_list:
		if match.tour<tournament.next_tour:
			match.home_team_points = match.home_team_points()#PlayerMatchResult.objects.filter(match = match, player__team=match.home_team).aggregate(match_points=Sum('points'))['match_points']
			match.visit_team_points = match.visit_team_points()#PlayerMatchResult.objects.filter(match = match, player__team=match.visit_team).aggregate(match_points=Sum('points'))['match_points']
			
	template = loader.get_template('matches.html')

	context = RequestContext(request, {'match_list': match_list, 'tournament':tournament})

	return HttpResponse(template.render(context))

def match_detail(request, tournament_id, match_id):
	
	tournament = Tournament.objects.get(id=tournament_id)

	match = Match.objects.get(id=match_id)

	home_results = PlayerMatchResult.objects.filter(match=match, player__team=match.home_team).order_by('-points')
	visit_results = PlayerMatchResult.objects.filter(match=match, player__team=match.visit_team).order_by('-points')
	
	template = loader.get_template('match.html')
	context = RequestContext(request, {'tournament':tournament, 'match': match, 'home_results':home_results, 'visit_results':visit_results})

	return HttpResponse(template.render(context))

def players(request, tournament_id):

	tournament = Tournament.objects.get(id = tournament_id)
	#points_count = PlayerMatchResult.objects.aggregate(total_points = Sum('points'))['total_points']
	players_list = Player.objects.filter(tournament_id = tournament_id).exclude(points=None).order_by('-points')

	for player in players_list:
		player.pmr = []
		pr = PlayerMatchResult.objects.filter(match__tournament_id=tournament_id).filter(player=player).filter(match__tour__lte=tournament.next_tour).order_by('match__tour')[:5]
		for p in pr:
			player.pmr.append(p.points)

	
	template = loader.get_template('players.html')
	context = RequestContext(request, {'players_list': players_list, 'tournament':tournament})


	return HttpResponse(template.render(context))

def player_detail(request, player_id, tournament_id):
	tournament = Tournament.objects.get(id=tournament_id)
	#points_count = PlayerMatchResult.objects.aggregate(total_points = Sum('points'))['total_points']
	player = Player.objects.get(id=player_id)
	pmr_list = PlayerMatchResult.objects.filter(player = player).order_by('match__tour')[:10]
	template = loader.get_template('player.html')
	context = RequestContext(request, {'player': player, 'pmr_list':pmr_list, 'tournament':tournament})

	return HttpResponse(template.render(context))

def team_detail(request, team_id, tournament_id):
	tournament = Tournament.objects.get(id=tournament_id)
	team = Team.objects.get(id=team_id, tournament = tournament)
	match_list = Match.objects.filter(tournament=tournament).filter(Q(visit_team=team)|Q(home_team=team)).exclude(tour__gte=tournament.next_tour).order_by('tour')[:10]
	
	team.match_list=match_list
	team.pmr = []
	for team.match in team.match_list:
		points = PlayerMatchResult.objects.filter(player__team = team, match=team.match).exclude(points=None).aggregate(tour_points=Sum('points'))['tour_points']
		team.match.points=points

	players_list = Player.objects.filter(tournament_id = tournament_id, team=team).exclude(points=None).order_by('-points')

	for player in players_list:
		player.pmr = []
		pr = PlayerMatchResult.objects.filter(match__tournament_id=tournament_id).filter(player=player).filter(match__tour__lte=tournament.next_tour).order_by('match__tour')[:5]
		for p in pr:
			player.pmr.append(p.points)

	template = loader.get_template('team.html')
	context = RequestContext(request, {'tournament':tournament, 'team': team, 'tour_results':team.match_list, 'players_list':players_list})

	return HttpResponse(template.render(context))

def pmr(request, tournament_id):

	tournament = Tournament.objects.get(id=tournament_id)

	players_list = Player.objects.filter(tournament=tournament).exclude(points=None).order_by('-points')[:100]

	template = loader.get_template('pmr.html')
	context = RequestContext(request, {'tournament': tournament, 'players_list':players_list})

	return HttpResponse(template.render(context))

players/templates/index.html
{% extends "base.html" %}


        <!-- Content Header (Page header) -->
          {% block title %}
          <h1>
            Доступные чемпионаты
            <small></small>
          </h1>
          {% endblock %}
{% block content %}
          <div class="row">
          {% for tournament in tournament_list %}
            <div class="col-lg-3 col-xs-6">    
              <div class="info-box">
                <span class="info-box-icon bg-green">
                    <i class="fa fa-flag-o">
                    </i>
                </span>
                <div class="info-box-content">
                <span class="info-box-text"><a href="{% url 'tournament_home' tournament.id %}">{{tournament.name}}</a></span>
                <span class="info-box-number">{{tournament.date|date:'d.m.Y'}}</span>
                </div>
              </div>
            </div>
          {% endfor %}
          </div>
{% endblock %}

players/templates/player.html
{% extends "base.html" %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
{{ block.super }}
{% breadcrumb tournament.name "tournament_home" tournament.id %}
{% breadcrumb "Игроки" "players" tournament.id  %}
{% breadcrumb player.name 'player_detail' player.id %}

{% endblock %}

          {% block title %}
          <h1>
            Статистика Игрока
            <small></small>
          </h1>
          {% endblock %}

{% block content %}
              <div class="row">
                <div class="col-sm-3">
                  <div class="box box-info">
                    <div class="box-header">
                      <h3 class="box-title">{{player.name}}</h3>
                      <img src={{player.url_img}}>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                                          
                       <div class="table-responsive">

                          <table class="table">
                              <tbody>
                                <tr>
                                  <th>Команда</th>
                                  <td>{{player.team.name}}</td>
                                </tr>
                                <tr>
                                  <th>Позиция</th>
                                  <td>{{player.get_amplua_display}}</td>
                                </tr>
                                <tr>
                                  <th>Цена</th>
                                  <td>{{player.price}}</td>
                                </tr>
                                <tr>
                                  <th>Очков</th>
                                  <td>{{player.points}}</td>
                                </tr>
                                <tr>
                                  <th>Голов</th>
                                  <td>{{player.goals}}</td>
                                </tr>
                                <tr>
                                  <th>Передач</th>
                                  <td>{{player.passes}}</td>
                                </tr>
                                <tr>
                                  <th>Сухих матчей</th>
                                  <td>{{player.clean_sheets}}</td>
                                </tr>
                                <tr>
                                  <th>Пользователей выбрало</th>
                                  <td>{{player.userchoosed}}</td>
                                </tr>
                              </tbody>
                          </table>
                        </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-9">
                  <div class="box box-info">
                    <table id="player" class="table table-striped table-bordered" cellspacing="0">
                      <thead>
                        <tr>
                          <th style="width:10px">#</th>
                          <th>Матч</th>
                          <th>Голы</th>
                          <th>Передачи</th>
                          <th>НП</th>
                          <th>ЖК</th>
                          <th >КК</th>
                          <th>СМ</th>
                          <th >Очки</th>
                          <th >Минут</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for pmr in pmr_list %}
                        <tr>
                          <td>{{forloop.counter}}</td>
                          <td>{{pmr.match.full_name}}</td>
                          <td>{{pmr.goals}}</td>
                          <td>{{pmr.passes}}</td>
                          <td>{{pmr.lose_penalty}}</td>
                          <td>{{pmr.yellow_cards}}</td>
                          <td>{{pmr.red_cards}}</td>
                          <td>{% if pmr.clean_sheet %}+{% endif %}</td>
                          <td>{{pmr.points}}</td>
                          <td>{{pmr.minute}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                  </div>
                </div>
              </div>
          <div class="row">
    <div class="col-md-12">
      <div id="container" style="width:100%; height:400px;"></div>
    </div>
    
  </div>
<script type="text/javascript">
  $(function () {
    $('#container').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: 'Турнир'
        },
        subtitle: {
            text: '{{tournament.name}}'
        },
        xAxis: {
            categories: [ {% for pmr in pmr_list %} "{{pmr.match.tour}} Тур", {% endfor %} ]
        },
        yAxis: {
            title: {
                text: 'Показатели'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },
        series: 
            [
            {
            name: '{{player.name}}',
            data: [{% for pmr in pmr_list %}{{pmr.points}}, {% endfor %}]
              },
            ]
    });
});
</script>
    <script type="text/javascript">
    $( document ).ready(function(){
        $('#match_table').DataTable({
          "paging": true,
          "searching": false,
          "lengthChange": false,
          "ordering": false,
          "info": false,
          "autoWidth": false
        });
      });
  </script>
{% endblock %}

players/templates/players.html
{% extends "base.html" %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
{{ block.super }}
{% breadcrumb tournament.name 'tournament_home' tournament.id %}
{% breadcrumb 'Игроки' 'players' %}
{% endblock %}

          {% block title %}
          <h1>
            Статистика игроков
            <small></small>
          </h1>
          {% endblock %}

{% block content %}
          <div class="box box-info">
                <div class="box-header">
                  <h3 class="box-title">Общие показатели</h3>
                </div><!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-sm-12">
                  <table id="players" class="table table-striped table-bordered" width="100%" cellspacing="0">
                    <thead>
                      <tr>
                        <th class="sortable" style="width: 10px">#</th>
                        <th>Имя</th>
                        <th>Команда</th>
                        <th>Цена</th>
                        <th>Амплуа</th>
                        <th>Прогресс</th>
                        <th >Очки</th>
                        <th>Г</th>
                        <th>П</th>
                        <th >СМ</th>
                        <th >5</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for player in players_list %}
                      <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href ="{% url 'player_detail' tournament.id player.id %}">{{player.name}}</a></td>
                        <td>{{player.team.name}}</td>
                        <td>{{player.price}}</td>
                        <td>{{player.get_amplua_display}}</td>
                        <td>
                          <div class="progress progress-xs progress-striped active">
                            <div class="progress-bar progress-bar-warning" style="width:{{player.points}}%"></div>
                          </div>
                        </td>
                        <td><span class="badge bg-orange">{{player.points}}</span></td>
                        <td>{{player.goals}}</td>
                        <td>{{player.passes}}</td>
                        <td>{{player.clean_sheets}}</td>
                        <td>
                        {% for p in player.pmr %}
                          <span class="badge bg-green">{{p}}</span>
                        {% endfor %}
                          </td>
                      </tr>
                      {% endfor %}
                      </tbody>
                    
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
    <script type="text/javascript">
    $( document ).ready(function(){
        $('#players').DataTable({
          "paging": true,
          "searching": true,
          "lengthChange": false,
          "iDisplayLength": 10,
          "ordering": true,
          "info": false,
          "autoWidth": true
        });
      });
  </script>
{% endblock %}

players/templates/pmr.html
{% extends "base.html" %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
{{ block.super }}
{% breadcrumb tournament.name 'tournament_home' tournament.id %}
{% breadcrumb 'Результаты' 'pmr' %}
{% endblock %}

          {% block title %}
          <h1>
            Результаты игроков
            <small></small>
          </h1>
          {% endblock %}

{% block content %}
          <div class="box box-info">
                <div class="box-header">
                  <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-sm-12">
                  <div id="container" style="width:100%; height:100%;"></div>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

<script type="text/javascript">
$(function () {
    $('#container').highcharts({

        chart: {
            type: 'bubble',
            zoomType: 'xy'
        },

        title: {
            text: 'Игроки'
        },

        series: [
        {% for player in players_list %}
        {
            name:'{{player.name}}',
            data: [[{{player.price}}, {{player.minutes}}, {{player.points}}]]
        }, 
        {% endfor %}
        ]
    });
});
</script>
{% endblock %}

players/templates/team.html
{% extends "base.html" %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb tournament.name "tournament_home" tournament.id %}
  {% breadcrumb "Команды" "teams" tournament.id %}
  {% breadcrumb team.name "team_detail" team.id %}
{% endblock %}

          {% block title %}
          <h1>
            Статистика команды
            <small></small>
          </h1>
          {% endblock %}

{% block content %}
              <div class="row">
                <div class="col-sm-3">
                    <p class="lead">{{team.name}}</p>
                  <div class="table-responsive">
                      <table class="table">
                          <tbody>
                            <tr>
                              <th>Место в лиге</th>
                              <td>{{team.place}}</td>
                            </tr>
                            <tr>
                              <th>Очков</th>
                              <td>{{team.points}}</td>
                            </tr>
                            <tr>
                              <th>Fantasy очков</th>
                              <td>{{team.fantasypoints}}</td>
                            </tr>
                            <tr>
                              <th>Победы</th>
                              <td>{{team.win}}</td>
                            </tr>
                            <tr>
                              <th>Поражения</th>
                              <td>{{team.lose}}</td>
                            </tr>
                            <tr>
                              <th>Ничьи</th>
                              <td>{{team.drawn}}</td>
                            </tr>
                            <tr>
                              <th>Забито</th>
                              <td>{{team.score_goals}}</td>
                            </tr>
                            <tr>
                              <th>Пропущено</th>
                              <td>{{team.lose_goals}}</td>
                            </tr>
                          </tbody>
                      </table>
                  </div>
                </div>
                <div class="col-md-9">
                  <div id="container_donut" style="width:100%; height:200px;"></div>
                  <div id="container" style="width:100%; height:200px;"></div>
                </div>
                
              </div>
          <div class="row">
            <div class="col-sm-12">
                  <div class="box box-info">
                    <table id="players" class="table table-striped table-bordered" width="100%" cellspacing="0">
                    <thead>
                      <tr>
                        <th class="sortable" style="width: 10px">#</th>
                        <th>Имя</th>
                        <th>Цена</th>
                        <th>Амплуа</th>
                        <th>Прогресс</th>
                        <th >Очки</th>
                        <th>Г</th>
                        <th>П</th>
                        <th >СМ</th>
                        <th >5</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for player in players_list %}
                      <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href ="{% url 'player_detail' tournament.id player.id %}">{{player.name}}</a></td>
                        <td>{{player.price}}</td>
                        <td>{{player.get_amplua_display}}</td>
                        <td>
                          <div class="progress progress-xs progress-striped active">
                            <div class="progress-bar progress-bar-warning" style="width:{{player.points}}%"></div>
                          </div>
                        </td>
                        <td><span class="badge bg-orange">{{player.points}}</span></td>
                        <td>{{player.goals}}</td>
                        <td>{{player.passes}}</td>
                        <td>{{player.clean_sheets}}</td>
                        <td>
                        {% for p in player.pmr %}
                          <span class="badge bg-green">{{p}}</span>
                        {% endfor %}
                          </td>
                      </tr>
                      {% endfor %}
                      </tbody>
                  </table>
                  </div>
                </div>
    
          </div>
<script type="text/javascript">
  $(function () {
    $('#container').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: 'Турнир'
        },
        subtitle: {
            text: '{{tournament.name}}'
        },
        xAxis: {
            categories: [ {% for tr in tour_results %} "{{tr.tour}} Тур", {% endfor %} ]
        },
        yAxis: {
            title: {
                text: 'Очки'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },
        series: 
            [
            {
            name: '{{team.name}}',
            data: [{% for tr in tour_results %}{{tr.points}}, {% endfor %}]
              },
            ]
    });
});
</script>
    <script type="text/javascript">
    $( document ).ready(function(){
        $('#players').DataTable({
          "paging": true,
          "searching": false,
          "lengthChange": false,
          "iDisplayLength": 10,
          "ordering": true,
          "info": false,
          "autoWidth": true
        });
      });
  </script>

<script type="text/javascript">
  $(function () {
    $('#container_donut').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: 0,
            plotShadow: false
        },
        title: {
            text: 'Статистика',
            align: 'center',
            verticalAlign: 'middle',
            y: 40
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                dataLabels: {
                    enabled: false,
                    distance: -50,
                    style: {
                        fontWeight: 'bold',
                        color: 'white',
                        textShadow: '0px 1px 2px black'
                    }
                },
                startAngle: -90,
                endAngle: 90,
                center: ['50%', '75%']
            }
        },
        series: [{
            type: 'pie',
            name: 'Очки',
            innerSize: '50%',
            data: [
                ['Вратари', {{team.goalkeeper_points}}],
                ['Защита', {{team.defs_points}}],
                ['Полузащита', {{team.mids_points}}],
                ['Нападение', {{team.forwards_points}}],
            ]
        }]
    });
});
</script>
{% endblock %}

players/templates/tournament_list.html
			<ul class="treeview-menu">
              {% for tournament in tournament_list %}
                <li><a href="/{{ tournament.id }}/">{{tournament.name}}</a></li>
              {% endfor %}
            </ul>